version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:6
    ports:
      - "6379:6379"

  smtp:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

  # web:
  #   build: .
  #   command: bundle exec rails s -b '0.0.0.0'
  #   volumes:
  #     - '.:/myapp'
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - cache
  #     - smtp
  #   environment:
  #     RAILS_ENV: development
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: password
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_NAME_DEVELOPMENT: myapp_development
  #     REDIS_URL: redis://redis:6379/1
  #     SMTP_ADDRESS: smtp
  #     SMTP_PORT: 1025

volumes:
  postgres_data: